name: autofix.ci

on:
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  ZIG_VERSION: 0.13.0

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Fix typos
        uses: crate-ci/typos@v1.26.8
        with:
          write_changes: true
      - run: zig fmt src test/harness tasks build.zig build.zig.zon

      - run: rm -f ./typos

      - uses: autofix-ci/action@dd55f44df8f7cdb7a6bf74c78677eb8acd40cd0a
