name: CI

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
    paths-ignore:
      - "*.md"
      - ".vscode/*"
      - zls.json
      - ".github/workflows/*"
      - "!.github/workflows/ci.yaml"
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - ".vscode/*"
      - zls.json
      - ".github/workflows/*"
      - "!.github/workflows/ci.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  ZIG_VERSION: 0.13.0

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Install tooling
      - uses: extractions/setup-just@v2
        with:
          just-version: ${{ env.JUST_VERSION }}
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ env.ZIG_VERSION }}
      # Run checks
      - run: just check

  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      # Install tooling
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: extractions/setup-just@v2
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ env.ZIG_VERSION }}
      # Run tests
      - run: zig build --fetch
      - run: zig build test --summary all -freference-trace --color on

  e2e:
    name: Test E2E
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Install tooling
      - uses: extractions/setup-just@v2
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ env.ZIG_VERSION }}
      - run: zig build --fetch
      - run: just submodules
      - run: just e2e
      - name: Check for changes
        run: git diff --exit-code

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Install tooling
      - uses: extractions/setup-just@v2
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ env.ZIG_VERSION }}
      - run: just docs
      - name: Check for changes
        run: git diff --exit-code
