name: CI

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
    paths-ignore:
      - "*.md"
      - ".vscode/*"
      - zls.json
      - ".github/ISSUE_TEMPLATE/*"
      - ".github/workflows/*"
      - "!.github/workflows/ci.yaml"
      - "apps/*"
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - ".vscode/*"
      - zls.json
      - ".github/ISSUE_TEMPLATE/*"
      - ".github/workflows/*"
      - "!.github/workflows/ci.yaml"
      - "apps/*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ZIG_VERSION: 0.14.1

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Install tooling
      - uses: extractions/setup-just@v2
        with:
          just-version: ${{ env.JUST_VERSION }}
      - uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}
      # Run checks
      - run: just check

  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      # Install tooling
      - uses: extractions/setup-just@v2
      - uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}
      # Run tests
      - run: zig build --fetch
      - run: zig build test --summary all -freference-trace --color on
      - name: Check for changes
        #  windows adds crlf line endings
        if: ${{ matrix.os != 'windows-latest' }}
        run: git diff --exit-code

  # https://imgflip.com/i/9eygz0
  lint:
    name: Lint Changed
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Install tooling
      - uses: extractions/setup-just@v2
      - uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}
      - run: zig build --fetch
      - run: zig build
      - uses: DonIsaac/zlint-action@v0
        with:
          binary: ./zig-out/bin/zlint

  e2e:
    name: Test E2E
    runs-on: ubuntu-latest
    strategy:
      matrix:
        optimize: ["ReleaseSafe", "ReleaseFast"]
    steps:
      - uses: actions/checkout@v4
      # Install tooling
      - uses: extractions/setup-just@v2
      - uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}
      - run: rm -rf ~/.cache/zig
      - run: zig build --fetch
      - run: just submodules
      - run: just e2e -Doptimize=${{ matrix.optimize }}
      - name: Check for changes
        run: git diff --exit-code

  docs:
    name: Docs + JSON Schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Install tooling
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: extractions/setup-just@v2
      - uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}
      - run: bun install --frozen-lockfile
      - run: zig build codegen --summary all
      - name: Check for changes
        run: git diff --exit-code
