name: CI

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
    paths-ignore:
      - "*.md"
      - ".vscode/*"
      - zls.json
      - ".github/workflows/*"
      - "!.github/workflows/ci.yaml"
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - ".vscode/*"
      - zls.json
      - ".github/workflows/*"
      - "!.github/workflows/ci.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ZIG_VERSION: 0.14.0

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Install tooling
      - uses: extractions/setup-just@v2
        with:
          just-version: ${{ env.JUST_VERSION }}
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ env.ZIG_VERSION }}
      # Run checks
      - run: just check

  build-debug:
    name: Build
    strategy:
      matrix:
        target:
        - os: linux
          arch: x86_64
        - os: macos
          arch: aarch64
        - os: windows
          arch: x86_64
        # os: [linux, macos, windows]
        # arch: [x86_64, aarch64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Install tooling
      - uses: extractions/setup-just@v2
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ env.ZIG_VERSION }}

      # Build
      - run: zig build --fetch
      - run: zig fmt src test/harness tasks build.zig build.zig.zon
      # - run: zig build check -Dtarget=${{ matrix.arch }}-${{ matrix.os }} -Dversion=${{ github.ref_name }}
      - run: |
          just build -Dtarget=${{ matrix.target.arch }}-${{ matrix.target.os }} 

      # upload artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          retention-days: 1
          compression-level: 2 # binaries don't compress well
          name: zlint-${{ matrix.target.os }}-${{ matrix.target.arch }}-${{ github.run_id }}
          path: zig-out/bin/**
          overwrite: true

  test:
    name: Test
    needs: build-debug
    strategy:
      matrix:
      # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners
        target:
          # kcov isn't available via apt-get on ubuntu-latest
          - runner: ubuntu-22.04
            os: linux
            arch: x86_64
          - runner: macos-latest
            os: macos
            arch: aarch64
          - runner: windows-latest
            os: windows
            arch: x86_64
      fail-fast: false
    runs-on: ${{ matrix.target.runner }}
    steps:
      - name: Install kcov
        if: ${{ matrix.target.os == 'linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y kcov
      # download compiled artifacts from build-debug for target platform
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: zlint-${{ matrix.target.os }}-${{ matrix.target.arch }}-${{ github.run_id }}
          path: zig-out/bin
          merge-multiple: true

      - run: ls -lA zig-out/bin

        # env:
        #   arch: ${{ steps.arch.outputs.architecture }}
        # with:
        #   name: zlint-${{ matrix.os }}-${{ env.arch }}-${{ github.ref }}
      - name: Test
        if: ${{ matrix.target.os != 'linux' }}
        run: |
          ./zig-out/bin/test
          ./zig-out/bin/test-utils

      - name: Test with Coverage
        if: ${{ matrix.target.os == 'linux' }}
        run: |
          mkdir -p ./.coverage
          test-bins=$(test test-utils)
          for test in $test-bins; do
            chmod +x zig-out/bin/$test
            kcov --include-path=src,test, ./.coverage/$test zig-out/bin/$test
          done

          kcov --merge ./.coverage/unit-test $(ls ./coverage)
      - name: Upload Coverage
        if: ${{ matrix.target.os == 'linux' }}
        uses: codecov/codecov-action@v4
        with:
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}

  # https://imgflip.com/i/9eygz0
  lint:
    name: Lint Changed
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Install tooling
      - uses: extractions/setup-just@v2
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ env.ZIG_VERSION }}
      - run: zig build --fetch
      - run: zig build
      - uses: DonIsaac/zlint-action@v0
        with:
          binary: ./zig-out/bin/zlint

  e2e:
    name: Test E2E
    runs-on: ubuntu-latest
    strategy:
      matrix:
        optimize: ["Debug", "ReleaseSafe", "ReleaseFast"]
    steps:
      - uses: actions/checkout@v4
      # Install tooling
      - uses: extractions/setup-just@v2
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ env.ZIG_VERSION }}
      - run: rm -rf ~/.cache/zig
      - run: zig build --fetch
      - run: just submodules
      - run: just e2e -Doptimize=${{ matrix.optimize }}
      - name: Check for changes
        run: git diff --exit-code

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Install tooling
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: extractions/setup-just@v2
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ env.ZIG_VERSION }}
      - run: just docs
      - name: Check for changes
        run: git diff --exit-code
