name: Codecov
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ZIG_VERSION: 0.14.1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codecov:
    name: Collect and upload test coverage
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v4
      - name: Install kcov
        run: |
          sudo apt-get update
          sudo apt-get install -y kcov
      - uses: extractions/setup-just@v2
      - uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - run: just submodules
      - run: zig build
      - run: just coverage
      - uses: codecov/codecov-action@v4
        with:
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
