name: Codecov
on:
  push:
    branches:
      - main

env:
  ZIG_VERSION: 0.13.0

concurrency:
  group: ${{ github.workflow }}

jobs:
  codecov:
    name: Collect and upload test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - run: zig build
      - run: just coverage
      - uses: codecov/codecov-action@v4
        with:
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
