name: JavaScript

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
    paths-ignore:
      - "*.zig"
      - "*.zon"
      - "*.snap"
      - "*.md"
      - "*.sh"
      - ".vscode/*"
      - ".github/*"
      - "!.github/workflows/js.yaml"
  push:
    branches:
      - main
    paths-ignore:
      - "*.zig"
      - "*.zon"
      - "*.snap"
      - "*.md"
      - "*.sh"
      - ".vscode/*"
      - ".github/*"
      - "!.github/workflows/js.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  BUN_VERSION: latest

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - name: Oxlint
        run: bunx oxlint@latest --format github -D correctness -D suspicious -D perf

  check-vscode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Typecheck
        working-directory: apps/vscode-extension
        run: bun tsc --noEmit

  check-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Typecheck
        working-directory: apps/site
        run: bun typecheck
      - name: Build
        working-directory: apps/site
        run: bun run build
        
