name: Label PR

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  pr:
    if: github.repository == 'DonIsaac/zlint'
    name: Label PR
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      - uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213 # v6.1.0
