name: Label PR

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  pr:
    if: github.repository == 'DonIsaac/zlint'
    name: Label PR
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d # v1.3.1
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5
