name: Release

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
env:
  ZIG_VERSION: 0.13.0

permissions:
  id-token: write
  contents: read
  attestations: write

jobs:
  build:
    strategy:
      matrix:
        # FIXME: handle windows paths in attestation and upload steps
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: zig build
        run: |
          zig build --summary all --color on --release=safe

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: zig-out/bin/zlint

      - name: Upload zlint binary
        uses: actions/upload-artifact@v4
        with:
          path: zig-out/bin/zlint
          name: zlint-${{ runner.os }}-${{ runner.arch }}
          retention-days: 1


# TODO
  # release:
  #   if: startsWith(github.ref, 'refs/tags/')
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Release
  #       uses: softprops/action-gh-release@v2
