name: ZLint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ZLint Action
        uses: DonIsaac/zlint-action@ff0119c6ac24408ff4285fab2cf83d8b1423cbdc
                  
